### ISSUE TITLE
Local Setup

### ISSUE THREAD

**Issue by rogeriochaves** [langwatch/langwatch#24]
We need to make it easier for anyone starting with the project to be able to run it on their machines, by having dependencies in docker and reducing the need of having all env vars to get started

@msnmz has progressed quite a bit on it already!

**Comment by darkacorn** [comment]
easy way would be just to supply a docker compose 
with db/elastic/redis/ and the app
also make some of the env's feature toggles as not everyone will need all options

**Comment by msnmz** [comment]
done with https://github.com/langwatch/langwatch/pull/31
