### ISSUE TITLE
Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by tm17-abcgen** [langwatch/langwatch#61]
The error in the title happens when e.g. the following is done when using the DSPy visualization feature of Langwatch:

` langwatch.dspy.init(experiment="miprov2:experiment1", optimizer=teleprompter)`

By coincidence i found out that using special characters will lead to that error, when i replace the ":" with a "-", the error is gone.
A function for sanitizing the experiment name is necessary, just in case :)

**Comment by rogeriochaves** [comment]
Hey there! Thank you very much for reporting, I've introduced `slugify` here to sanitize the experiment slug but added a name field to keep the original name on the frontend

It's fixed on 1c7218bcf5d444df614579ea53172563a1c07c1e now :)

![image](https://github.com/user-attachments/assets/ad4501c4-bb06-45c6-af2b-1dc363234d42)

![image](https://github.com/user-attachments/assets/988b23f6-bb61-4c2f-a37e-5f31b1ed89b5)
