### ISSUE TITLE
Basic Auth to Elastic/OpenSearch?

### ISSUE THREAD

**Issue by nundys** [langwatch/langwatch#65]
Hi:

For those of us who use OpenSearch (AWS-supported fork of Elasticsearch), we can't integrate into our existing domains because Langwatch uses an API key, but not Basic Auth based Security as used in OpenSearch https://opensearch.org/docs/latest/security/authentication-backends/basic-authc/

Any chance that could be implemented?  Would add a lot of users who already use a hardened search service on AWS.

Thanks

**Comment by rogeriochaves** [comment]
Hey there @nundys, basic auth should actually work already, you can simply skip `ELASTICSEARCH_API_KEY` and add the credentials directly on `ELASTICSEARCH_NODE_URL`, for example: `https://user:password@elasticsearch:9200`

however, you might face one other issue other than the authentication to make it work with OpenSearch, which is the vector storage. We use embeddings of the messages to allow for semantic search, and the way ES and OpenSearch store and query them are a bit different, but we wanted to make it compatible with both indeed, maybe by adding an env var `IS_OPENSEARCH` that would control that

would you be willing to contribute and help us out with that? The main files to look at would be `elasticIndexCreate.ts` on the `embeddings` fields for the dense vector creation on the index and the `routers/traces.ts` file for the knn query, and you should be good to go!

**Comment by rogeriochaves** [comment]
hey @nundys, we actually changed our opensource implementation to support opensearch rather than elasticsearch by default! It all works 100%. Let me know if you can give it another try, an if any issues, closing this for now
